name: MurderMystery
version: '${version}'

main: net.saturn.murderMystery.MurderMystery
api-version: '1.21'
load: STARTUP

authors: [ PumpkinDev ]

permissions:
  murdermystery.admin:
    description: Access to admin commands (start, stop)
    default: op